<html>
<head>
<?php
echo '

<title>'Hello Kyms world'</title>;
?>
</head>
<body>
<?php
       echo '<p>This content was generated by Kym</p>';
?>
<p>And this content is static HTML</p>
</body>
</html>